spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://:5432/services
    username:
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect