spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: